function formatFigure()
    set(gcf,'Units','normalized','OuterPosition',[0 0 1 1],'Color','w')

    ax = findall(gcf,'Type','axes');
    set(ax, ...
        'LineWidth', 4, ...
        'FontSize', 25, ...
        'Box', 'off', ...
        'Color', 'w', ...
        'XGrid', 'off', ...
        'YGrid', 'off', ...
        'XMinorGrid', 'off', ...
        'YMinorGrid', 'off');
end